/********************************************************
 *          Copyright(c) 2019   Semidrive               *
 ********************************************************/

/* Generated by tool. Do not modify manually. */

#ifndef __DW_APB_UART_REG_H__
#define __DW_APB_UART_REG_H__

#define RBR_OFF 0x0U

#define FM_RBR_RSVD_RBR (0x7fffffU << 9U)
#define FV_RBR_RSVD_RBR(v) \
    (((v) << 9U) & FM_RBR_RSVD_RBR)
#define GFV_RBR_RSVD_RBR(v) \
    (((v) & FM_RBR_RSVD_RBR) >> 9U)

#define FM_RBR_RBR  (0x1ffU << 0U)
#define FV_RBR_RBR(v) \
    (((v) << 0U) & FM_RBR_RBR)
#define GFV_RBR_RBR(v) \
    (((v) & FM_RBR_RBR) >> 0U)

#define IER_OFF 0x4U

#define FM_IER_RSVD_IER_31TO8   (0xffffffU << 8U)
#define FV_IER_RSVD_IER_31TO8(v) \
    (((v) << 8U) & FM_IER_RSVD_IER_31TO8)
#define GFV_IER_RSVD_IER_31TO8(v) \
    (((v) & FM_IER_RSVD_IER_31TO8) >> 8U)

#define BM_IER_PTIME    (0x01U << 7U)

#define FM_IER_RSVD_IER_6TO5    (0x3U << 5U)
#define FV_IER_RSVD_IER_6TO5(v) \
    (((v) << 5U) & FM_IER_RSVD_IER_6TO5)
#define GFV_IER_RSVD_IER_6TO5(v) \
    (((v) & FM_IER_RSVD_IER_6TO5) >> 5U)

#define BM_IER_ELCOLR   (0x01U << 4U)

#define BM_IER_EDSSI    (0x01U << 3U)

#define BM_IER_ELSI (0x01U << 2U)

#define BM_IER_ETBEI    (0x01U << 1U)

#define BM_IER_ERBFI    (0x01U << 0U)

#define IIR_OFF 0x8U

#define FM_IIR_RSVD_IIR_31TO8   (0xffffffU << 8U)
#define FV_IIR_RSVD_IIR_31TO8(v) \
    (((v) << 8U) & FM_IIR_RSVD_IIR_31TO8)
#define GFV_IIR_RSVD_IIR_31TO8(v) \
    (((v) & FM_IIR_RSVD_IIR_31TO8) >> 8U)

#define FM_IIR_FIFOSE   (0x3U << 6U)
#define FV_IIR_FIFOSE(v) \
    (((v) << 6U) & FM_IIR_FIFOSE)
#define GFV_IIR_FIFOSE(v) \
    (((v) & FM_IIR_FIFOSE) >> 6U)

#define FM_IIR_RSVD_IIR_5TO4    (0x3U << 4U)
#define FV_IIR_RSVD_IIR_5TO4(v) \
    (((v) << 4U) & FM_IIR_RSVD_IIR_5TO4)
#define GFV_IIR_RSVD_IIR_5TO4(v) \
    (((v) & FM_IIR_RSVD_IIR_5TO4) >> 4U)

#define FM_IIR_IID  (0xfU << 0U)
#define FV_IIR_IID(v) \
    (((v) << 0U) & FM_IIR_IID)
#define GFV_IIR_IID(v) \
    (((v) & FM_IIR_IID) >> 0U)

#define LCR_OFF 0xcU

#define FM_LCR_RSVD_LCR_31TO8   (0xffffffU << 8U)
#define FV_LCR_RSVD_LCR_31TO8(v) \
    (((v) << 8U) & FM_LCR_RSVD_LCR_31TO8)
#define GFV_LCR_RSVD_LCR_31TO8(v) \
    (((v) & FM_LCR_RSVD_LCR_31TO8) >> 8U)

#define BM_LCR_DLAB (0x01U << 7U)

#define BM_LCR_BC   (0x01U << 6U)

#define BM_LCR_SP   (0x01U << 5U)

#define BM_LCR_EPS  (0x01U << 4U)

#define BM_LCR_PEN  (0x01U << 3U)

#define BM_LCR_STOP (0x01U << 2U)

#define FM_LCR_DLS  (0x3U << 0U)
#define FV_LCR_DLS(v) \
    (((v) << 0U) & FM_LCR_DLS)
#define GFV_LCR_DLS(v) \
    (((v) & FM_LCR_DLS) >> 0U)

#define MCR_OFF 0x10U

#define FM_MCR_RSVD_MCR_31TO7   (0x1ffffffU << 7U)
#define FV_MCR_RSVD_MCR_31TO7(v) \
    (((v) << 7U) & FM_MCR_RSVD_MCR_31TO7)
#define GFV_MCR_RSVD_MCR_31TO7(v) \
    (((v) & FM_MCR_RSVD_MCR_31TO7) >> 7U)

#define BM_MCR_SIRE (0x01U << 6U)

#define BM_MCR_AFCE (0x01U << 5U)

#define BM_MCR_LOOPBACK (0x01U << 4U)

#define BM_MCR_OUT2 (0x01U << 3U)

#define BM_MCR_OUT1 (0x01U << 2U)

#define BM_MCR_RTS  (0x01U << 1U)

#define BM_MCR_DTR  (0x01U << 0U)

#define LSR_OFF 0x14U

#define FM_LSR_RSVD_LSR_31TO9   (0x7fffffU << 9U)
#define FV_LSR_RSVD_LSR_31TO9(v) \
    (((v) << 9U) & FM_LSR_RSVD_LSR_31TO9)
#define GFV_LSR_RSVD_LSR_31TO9(v) \
    (((v) & FM_LSR_RSVD_LSR_31TO9) >> 9U)

#define BM_LSR_ADDR_RCVD    (0x01U << 8U)

#define BM_LSR_RFE  (0x01U << 7U)

#define BM_LSR_TEMT (0x01U << 6U)

#define BM_LSR_THRE (0x01U << 5U)

#define BM_LSR_BI   (0x01U << 4U)

#define BM_LSR_FE   (0x01U << 3U)

#define BM_LSR_PE   (0x01U << 2U)

#define BM_LSR_OE   (0x01U << 1U)

#define BM_LSR_DR   (0x01U << 0U)

#define MSR_OFF 0x18U

#define FM_MSR_RSVD_MSR_31TO8   (0xffffffU << 8U)
#define FV_MSR_RSVD_MSR_31TO8(v) \
    (((v) << 8U) & FM_MSR_RSVD_MSR_31TO8)
#define GFV_MSR_RSVD_MSR_31TO8(v) \
    (((v) & FM_MSR_RSVD_MSR_31TO8) >> 8U)

#define BM_MSR_DCD  (0x01U << 7U)

#define BM_MSR_RI   (0x01U << 6U)

#define BM_MSR_DSR  (0x01U << 5U)

#define BM_MSR_CTS  (0x01U << 4U)

#define BM_MSR_DDCD (0x01U << 3U)

#define BM_MSR_TERI (0x01U << 2U)

#define BM_MSR_DDSR (0x01U << 1U)

#define BM_MSR_DCTS (0x01U << 0U)

#define SCR_OFF 0x1cU

#define FM_SCR_RSVD_SCR_31TO8   (0xffffffU << 8U)
#define FV_SCR_RSVD_SCR_31TO8(v) \
    (((v) << 8U) & FM_SCR_RSVD_SCR_31TO8)
#define GFV_SCR_RSVD_SCR_31TO8(v) \
    (((v) & FM_SCR_RSVD_SCR_31TO8) >> 8U)

#define FM_SCR_SCR  (0xffU << 0U)
#define FV_SCR_SCR(v) \
    (((v) << 0U) & FM_SCR_SCR)
#define GFV_SCR_SCR(v) \
    (((v) & FM_SCR_SCR) >> 0U)

#define SRBR0_OFF   0x30U

#define FM_SRBR0_RSVD_SRBRN (0x7fffffU << 9U)
#define FV_SRBR0_RSVD_SRBRN(v) \
    (((v) << 9U) & FM_SRBR0_RSVD_SRBRN)
#define GFV_SRBR0_RSVD_SRBRN(v) \
    (((v) & FM_SRBR0_RSVD_SRBRN) >> 9U)

#define FM_SRBR0_SRBRN  (0x1ffU << 0U)
#define FV_SRBR0_SRBRN(v) \
    (((v) << 0U) & FM_SRBR0_SRBRN)
#define GFV_SRBR0_SRBRN(v) \
    (((v) & FM_SRBR0_SRBRN) >> 0U)

#define SRBR1_OFF   0x34U

#define FM_SRBR1_RSVD_SRBR1 (0x7fffffU << 9U)
#define FV_SRBR1_RSVD_SRBR1(v) \
    (((v) << 9U) & FM_SRBR1_RSVD_SRBR1)
#define GFV_SRBR1_RSVD_SRBR1(v) \
    (((v) & FM_SRBR1_RSVD_SRBR1) >> 9U)

#define FM_SRBR1_SRBR1  (0x1ffU << 0U)
#define FV_SRBR1_SRBR1(v) \
    (((v) << 0U) & FM_SRBR1_SRBR1)
#define GFV_SRBR1_SRBR1(v) \
    (((v) & FM_SRBR1_SRBR1) >> 0U)

#define SRBR2_OFF   0x38U

#define FM_SRBR2_RSVD_SRBR2 (0x7fffffU << 9U)
#define FV_SRBR2_RSVD_SRBR2(v) \
    (((v) << 9U) & FM_SRBR2_RSVD_SRBR2)
#define GFV_SRBR2_RSVD_SRBR2(v) \
    (((v) & FM_SRBR2_RSVD_SRBR2) >> 9U)

#define FM_SRBR2_SRBR2  (0x1ffU << 0U)
#define FV_SRBR2_SRBR2(v) \
    (((v) << 0U) & FM_SRBR2_SRBR2)
#define GFV_SRBR2_SRBR2(v) \
    (((v) & FM_SRBR2_SRBR2) >> 0U)

#define SRBR3_OFF   0x3cU

#define FM_SRBR3_RSVD_SRBR3 (0x7fffffU << 9U)
#define FV_SRBR3_RSVD_SRBR3(v) \
    (((v) << 9U) & FM_SRBR3_RSVD_SRBR3)
#define GFV_SRBR3_RSVD_SRBR3(v) \
    (((v) & FM_SRBR3_RSVD_SRBR3) >> 9U)

#define FM_SRBR3_SRBR3  (0x1ffU << 0U)
#define FV_SRBR3_SRBR3(v) \
    (((v) << 0U) & FM_SRBR3_SRBR3)
#define GFV_SRBR3_SRBR3(v) \
    (((v) & FM_SRBR3_SRBR3) >> 0U)

#define SRBR4_OFF   0x40U

#define FM_SRBR4_RSVD_SRBR4 (0x7fffffU << 9U)
#define FV_SRBR4_RSVD_SRBR4(v) \
    (((v) << 9U) & FM_SRBR4_RSVD_SRBR4)
#define GFV_SRBR4_RSVD_SRBR4(v) \
    (((v) & FM_SRBR4_RSVD_SRBR4) >> 9U)

#define FM_SRBR4_SRBR4  (0x1ffU << 0U)
#define FV_SRBR4_SRBR4(v) \
    (((v) << 0U) & FM_SRBR4_SRBR4)
#define GFV_SRBR4_SRBR4(v) \
    (((v) & FM_SRBR4_SRBR4) >> 0U)

#define SRBR5_OFF   0x44U

#define FM_SRBR5_RSVD_SRBR5 (0x7fffffU << 9U)
#define FV_SRBR5_RSVD_SRBR5(v) \
    (((v) << 9U) & FM_SRBR5_RSVD_SRBR5)
#define GFV_SRBR5_RSVD_SRBR5(v) \
    (((v) & FM_SRBR5_RSVD_SRBR5) >> 9U)

#define FM_SRBR5_SRBR5  (0x1ffU << 0U)
#define FV_SRBR5_SRBR5(v) \
    (((v) << 0U) & FM_SRBR5_SRBR5)
#define GFV_SRBR5_SRBR5(v) \
    (((v) & FM_SRBR5_SRBR5) >> 0U)

#define SRBR6_OFF   0x48U

#define FM_SRBR6_RSVD_SRBR6 (0x7fffffU << 9U)
#define FV_SRBR6_RSVD_SRBR6(v) \
    (((v) << 9U) & FM_SRBR6_RSVD_SRBR6)
#define GFV_SRBR6_RSVD_SRBR6(v) \
    (((v) & FM_SRBR6_RSVD_SRBR6) >> 9U)

#define FM_SRBR6_SRBR6  (0x1ffU << 0U)
#define FV_SRBR6_SRBR6(v) \
    (((v) << 0U) & FM_SRBR6_SRBR6)
#define GFV_SRBR6_SRBR6(v) \
    (((v) & FM_SRBR6_SRBR6) >> 0U)

#define SRBR7_OFF   0x4cU

#define FM_SRBR7_RSVD_SRBR7 (0x7fffffU << 9U)
#define FV_SRBR7_RSVD_SRBR7(v) \
    (((v) << 9U) & FM_SRBR7_RSVD_SRBR7)
#define GFV_SRBR7_RSVD_SRBR7(v) \
    (((v) & FM_SRBR7_RSVD_SRBR7) >> 9U)

#define FM_SRBR7_SRBR7  (0x1ffU << 0U)
#define FV_SRBR7_SRBR7(v) \
    (((v) << 0U) & FM_SRBR7_SRBR7)
#define GFV_SRBR7_SRBR7(v) \
    (((v) & FM_SRBR7_SRBR7) >> 0U)

#define SRBR8_OFF   0x50U

#define FM_SRBR8_RSVD_SRBR8 (0x7fffffU << 9U)
#define FV_SRBR8_RSVD_SRBR8(v) \
    (((v) << 9U) & FM_SRBR8_RSVD_SRBR8)
#define GFV_SRBR8_RSVD_SRBR8(v) \
    (((v) & FM_SRBR8_RSVD_SRBR8) >> 9U)

#define FM_SRBR8_SRBR8  (0x1ffU << 0U)
#define FV_SRBR8_SRBR8(v) \
    (((v) << 0U) & FM_SRBR8_SRBR8)
#define GFV_SRBR8_SRBR8(v) \
    (((v) & FM_SRBR8_SRBR8) >> 0U)

#define SRBR9_OFF   0x54U

#define FM_SRBR9_RSVD_SRBR9 (0x7fffffU << 9U)
#define FV_SRBR9_RSVD_SRBR9(v) \
    (((v) << 9U) & FM_SRBR9_RSVD_SRBR9)
#define GFV_SRBR9_RSVD_SRBR9(v) \
    (((v) & FM_SRBR9_RSVD_SRBR9) >> 9U)

#define FM_SRBR9_SRBR9  (0x1ffU << 0U)
#define FV_SRBR9_SRBR9(v) \
    (((v) << 0U) & FM_SRBR9_SRBR9)
#define GFV_SRBR9_SRBR9(v) \
    (((v) & FM_SRBR9_SRBR9) >> 0U)

#define SRBR10_OFF  0x58U

#define FM_SRBR10_RSVD_SRBR10   (0x7fffffU << 9U)
#define FV_SRBR10_RSVD_SRBR10(v) \
    (((v) << 9U) & FM_SRBR10_RSVD_SRBR10)
#define GFV_SRBR10_RSVD_SRBR10(v) \
    (((v) & FM_SRBR10_RSVD_SRBR10) >> 9U)

#define FM_SRBR10_SRBR10    (0x1ffU << 0U)
#define FV_SRBR10_SRBR10(v) \
    (((v) << 0U) & FM_SRBR10_SRBR10)
#define GFV_SRBR10_SRBR10(v) \
    (((v) & FM_SRBR10_SRBR10) >> 0U)

#define SRBR11_OFF  0x5cU

#define FM_SRBR11_RSVD_SRBR11   (0x7fffffU << 9U)
#define FV_SRBR11_RSVD_SRBR11(v) \
    (((v) << 9U) & FM_SRBR11_RSVD_SRBR11)
#define GFV_SRBR11_RSVD_SRBR11(v) \
    (((v) & FM_SRBR11_RSVD_SRBR11) >> 9U)

#define FM_SRBR11_SRBR11    (0x1ffU << 0U)
#define FV_SRBR11_SRBR11(v) \
    (((v) << 0U) & FM_SRBR11_SRBR11)
#define GFV_SRBR11_SRBR11(v) \
    (((v) & FM_SRBR11_SRBR11) >> 0U)

#define SRBR12_OFF  0x60U

#define FM_SRBR12_RSVD_SRBR12   (0x7fffffU << 9U)
#define FV_SRBR12_RSVD_SRBR12(v) \
    (((v) << 9U) & FM_SRBR12_RSVD_SRBR12)
#define GFV_SRBR12_RSVD_SRBR12(v) \
    (((v) & FM_SRBR12_RSVD_SRBR12) >> 9U)

#define FM_SRBR12_SRBR12    (0x1ffU << 0U)
#define FV_SRBR12_SRBR12(v) \
    (((v) << 0U) & FM_SRBR12_SRBR12)
#define GFV_SRBR12_SRBR12(v) \
    (((v) & FM_SRBR12_SRBR12) >> 0U)

#define SRBR13_OFF  0x64U

#define FM_SRBR13_RSVD_SRBR13   (0x7fffffU << 9U)
#define FV_SRBR13_RSVD_SRBR13(v) \
    (((v) << 9U) & FM_SRBR13_RSVD_SRBR13)
#define GFV_SRBR13_RSVD_SRBR13(v) \
    (((v) & FM_SRBR13_RSVD_SRBR13) >> 9U)

#define FM_SRBR13_SRBR13    (0x1ffU << 0U)
#define FV_SRBR13_SRBR13(v) \
    (((v) << 0U) & FM_SRBR13_SRBR13)
#define GFV_SRBR13_SRBR13(v) \
    (((v) & FM_SRBR13_SRBR13) >> 0U)

#define SRBR14_OFF  0x68U

#define FM_SRBR14_RSVD_SRBR14   (0x7fffffU << 9U)
#define FV_SRBR14_RSVD_SRBR14(v) \
    (((v) << 9U) & FM_SRBR14_RSVD_SRBR14)
#define GFV_SRBR14_RSVD_SRBR14(v) \
    (((v) & FM_SRBR14_RSVD_SRBR14) >> 9U)

#define FM_SRBR14_SRBR14    (0x1ffU << 0U)
#define FV_SRBR14_SRBR14(v) \
    (((v) << 0U) & FM_SRBR14_SRBR14)
#define GFV_SRBR14_SRBR14(v) \
    (((v) & FM_SRBR14_SRBR14) >> 0U)

#define SRBR15_OFF  0x6cU

#define FM_SRBR15_RSVD_SRBR15   (0x7fffffU << 9U)
#define FV_SRBR15_RSVD_SRBR15(v) \
    (((v) << 9U) & FM_SRBR15_RSVD_SRBR15)
#define GFV_SRBR15_RSVD_SRBR15(v) \
    (((v) & FM_SRBR15_RSVD_SRBR15) >> 9U)

#define FM_SRBR15_SRBR15    (0x1ffU << 0U)
#define FV_SRBR15_SRBR15(v) \
    (((v) << 0U) & FM_SRBR15_SRBR15)
#define GFV_SRBR15_SRBR15(v) \
    (((v) & FM_SRBR15_SRBR15) >> 0U)

#define FAR_OFF 0x70U

#define FM_FAR_RSVD_FAR_31TO1   (0x7fffffffU << 1U)
#define FV_FAR_RSVD_FAR_31TO1(v) \
    (((v) << 1U) & FM_FAR_RSVD_FAR_31TO1)
#define GFV_FAR_RSVD_FAR_31TO1(v) \
    (((v) & FM_FAR_RSVD_FAR_31TO1) >> 1U)

#define BM_FAR_FAR  (0x01U << 0U)

#define TFR_OFF 0x74U

#define FM_TFR_RSVD_TFR_31TO8   (0xffffffU << 8U)
#define FV_TFR_RSVD_TFR_31TO8(v) \
    (((v) << 8U) & FM_TFR_RSVD_TFR_31TO8)
#define GFV_TFR_RSVD_TFR_31TO8(v) \
    (((v) & FM_TFR_RSVD_TFR_31TO8) >> 8U)

#define FM_TFR_TFR  (0xffU << 0U)
#define FV_TFR_TFR(v) \
    (((v) << 0U) & FM_TFR_TFR)
#define GFV_TFR_TFR(v) \
    (((v) & FM_TFR_TFR) >> 0U)

#define RFW_OFF 0x78U

#define FM_RFW_RSVD_RFW_31TO10  (0x3fffffU << 10U)
#define FV_RFW_RSVD_RFW_31TO10(v) \
    (((v) << 10U) & FM_RFW_RSVD_RFW_31TO10)
#define GFV_RFW_RSVD_RFW_31TO10(v) \
    (((v) & FM_RFW_RSVD_RFW_31TO10) >> 10U)

#define BM_RFW_RFFE (0x01U << 9U)

#define BM_RFW_RFPE (0x01U << 8U)

#define FM_RFW_RFWD (0xffU << 0U)
#define FV_RFW_RFWD(v) \
    (((v) << 0U) & FM_RFW_RFWD)
#define GFV_RFW_RFWD(v) \
    (((v) & FM_RFW_RFWD) >> 0U)

#define USR_OFF 0x7cU

#define FM_USR_RSVD_USR_31TO5   (0x7ffffffU << 5U)
#define FV_USR_RSVD_USR_31TO5(v) \
    (((v) << 5U) & FM_USR_RSVD_USR_31TO5)
#define GFV_USR_RSVD_USR_31TO5(v) \
    (((v) & FM_USR_RSVD_USR_31TO5) >> 5U)

#define BM_USR_RFF  (0x01U << 4U)

#define BM_USR_RFNE (0x01U << 3U)

#define BM_USR_TFE  (0x01U << 2U)

#define BM_USR_TFNF (0x01U << 1U)

#define BM_USR_RSVD_BUSY    (0x01U << 0U)

#define TFL_OFF 0x80U

#define FM_TFL_RSVD_TFL_31TOADDR_WIDTH  (0x3ffffffU << 6U)
#define FV_TFL_RSVD_TFL_31TOADDR_WIDTH(v) \
    (((v) << 6U) & FM_TFL_RSVD_TFL_31TOADDR_WIDTH)
#define GFV_TFL_RSVD_TFL_31TOADDR_WIDTH(v) \
    (((v) & FM_TFL_RSVD_TFL_31TOADDR_WIDTH) >> 6U)

#define FM_TFL_TFL  (0x3fU << 0U)
#define FV_TFL_TFL(v) \
    (((v) << 0U) & FM_TFL_TFL)
#define GFV_TFL_TFL(v) \
    (((v) & FM_TFL_TFL) >> 0U)

#define RFL_OFF 0x84U

#define FM_RFL_RSVD_RFL_31TOADDR_WIDTH  (0x3ffffffU << 6U)
#define FV_RFL_RSVD_RFL_31TOADDR_WIDTH(v) \
    (((v) << 6U) & FM_RFL_RSVD_RFL_31TOADDR_WIDTH)
#define GFV_RFL_RSVD_RFL_31TOADDR_WIDTH(v) \
    (((v) & FM_RFL_RSVD_RFL_31TOADDR_WIDTH) >> 6U)

#define FM_RFL_RFL  (0x3fU << 0U)
#define FV_RFL_RFL(v) \
    (((v) << 0U) & FM_RFL_RFL)
#define GFV_RFL_RFL(v) \
    (((v) & FM_RFL_RFL) >> 0U)

#define SRR_OFF 0x88U

#define FM_SRR_RSVD_SRR_31TO3   (0x1fffffffU << 3U)
#define FV_SRR_RSVD_SRR_31TO3(v) \
    (((v) << 3U) & FM_SRR_RSVD_SRR_31TO3)
#define GFV_SRR_RSVD_SRR_31TO3(v) \
    (((v) & FM_SRR_RSVD_SRR_31TO3) >> 3U)

#define BM_SRR_XFR  (0x01U << 2U)

#define BM_SRR_RFR  (0x01U << 1U)

#define BM_SRR_UR   (0x01U << 0U)

#define SRTS_OFF    0x8cU

#define FM_SRTS_RSVD_SRTS_31TO1 (0x7fffffffU << 1U)
#define FV_SRTS_RSVD_SRTS_31TO1(v) \
    (((v) << 1U) & FM_SRTS_RSVD_SRTS_31TO1)
#define GFV_SRTS_RSVD_SRTS_31TO1(v) \
    (((v) & FM_SRTS_RSVD_SRTS_31TO1) >> 1U)

#define BM_SRTS_SRTS    (0x01U << 0U)

#define SBCR_OFF    0x90U

#define FM_SBCR_RSVD_SBCR_31TO1 (0x7fffffffU << 1U)
#define FV_SBCR_RSVD_SBCR_31TO1(v) \
    (((v) << 1U) & FM_SBCR_RSVD_SBCR_31TO1)
#define GFV_SBCR_RSVD_SBCR_31TO1(v) \
    (((v) & FM_SBCR_RSVD_SBCR_31TO1) >> 1U)

#define BM_SBCR_SBCB    (0x01U << 0U)

#define SDMAM_OFF   0x94U

#define FM_SDMAM_RSVD_SDMAM_31TO1   (0x7fffffffU << 1U)
#define FV_SDMAM_RSVD_SDMAM_31TO1(v) \
    (((v) << 1U) & FM_SDMAM_RSVD_SDMAM_31TO1)
#define GFV_SDMAM_RSVD_SDMAM_31TO1(v) \
    (((v) & FM_SDMAM_RSVD_SDMAM_31TO1) >> 1U)

#define BM_SDMAM_SDMAM  (0x01U << 0U)

#define SFE_OFF 0x98U

#define FM_SFE_RSVD_SFE_31TO1   (0x7fffffffU << 1U)
#define FV_SFE_RSVD_SFE_31TO1(v) \
    (((v) << 1U) & FM_SFE_RSVD_SFE_31TO1)
#define GFV_SFE_RSVD_SFE_31TO1(v) \
    (((v) & FM_SFE_RSVD_SFE_31TO1) >> 1U)

#define BM_SFE_SFE  (0x01U << 0U)

#define SRT_OFF 0x9cU

#define FM_SRT_RSVD_SRT_31TO2   (0x3fffffffU << 2U)
#define FV_SRT_RSVD_SRT_31TO2(v) \
    (((v) << 2U) & FM_SRT_RSVD_SRT_31TO2)
#define GFV_SRT_RSVD_SRT_31TO2(v) \
    (((v) & FM_SRT_RSVD_SRT_31TO2) >> 2U)

#define FM_SRT_SRT  (0x3U << 0U)
#define FV_SRT_SRT(v) \
    (((v) << 0U) & FM_SRT_SRT)
#define GFV_SRT_SRT(v) \
    (((v) & FM_SRT_SRT) >> 0U)

#define STET_OFF    0xa0U

#define FM_STET_RSVD_STET_31TO2 (0x3fffffffU << 2U)
#define FV_STET_RSVD_STET_31TO2(v) \
    (((v) << 2U) & FM_STET_RSVD_STET_31TO2)
#define GFV_STET_RSVD_STET_31TO2(v) \
    (((v) & FM_STET_RSVD_STET_31TO2) >> 2U)

#define FM_STET_STET    (0x3U << 0U)
#define FV_STET_STET(v) \
    (((v) << 0U) & FM_STET_STET)
#define GFV_STET_STET(v) \
    (((v) & FM_STET_STET) >> 0U)

#define HTX_OFF 0xa4U

#define FM_HTX_RSVD_HTX_31TO1   (0x7fffffffU << 1U)
#define FV_HTX_RSVD_HTX_31TO1(v) \
    (((v) << 1U) & FM_HTX_RSVD_HTX_31TO1)
#define GFV_HTX_RSVD_HTX_31TO1(v) \
    (((v) & FM_HTX_RSVD_HTX_31TO1) >> 1U)

#define BM_HTX_HTX  (0x01U << 0U)

#define DMASA_OFF   0xa8U

#define FM_DMASA_RSVD_DMASA_31TO1   (0x7fffffffU << 1U)
#define FV_DMASA_RSVD_DMASA_31TO1(v) \
    (((v) << 1U) & FM_DMASA_RSVD_DMASA_31TO1)
#define GFV_DMASA_RSVD_DMASA_31TO1(v) \
    (((v) & FM_DMASA_RSVD_DMASA_31TO1) >> 1U)

#define BM_DMASA_DMASA  (0x01U << 0U)

#define TCR_OFF 0xacU

#define FM_TCR_RSVD_TCR_31TO5   (0x7ffffffU << 5U)
#define FV_TCR_RSVD_TCR_31TO5(v) \
    (((v) << 5U) & FM_TCR_RSVD_TCR_31TO5)
#define GFV_TCR_RSVD_TCR_31TO5(v) \
    (((v) & FM_TCR_RSVD_TCR_31TO5) >> 5U)

#define FM_TCR_XFER_MODE    (0x3U << 3U)
#define FV_TCR_XFER_MODE(v) \
    (((v) << 3U) & FM_TCR_XFER_MODE)
#define GFV_TCR_XFER_MODE(v) \
    (((v) & FM_TCR_XFER_MODE) >> 3U)

#define BM_TCR_DE_POL   (0x01U << 2U)

#define BM_TCR_RE_POL   (0x01U << 1U)

#define BM_TCR_RS485_EN (0x01U << 0U)

#define DE_EN_OFF   0xb0U

#define FM_DE_EN_RSVD_DE_EN_31TO1   (0x7fffffffU << 1U)
#define FV_DE_EN_RSVD_DE_EN_31TO1(v) \
    (((v) << 1U) & FM_DE_EN_RSVD_DE_EN_31TO1)
#define GFV_DE_EN_RSVD_DE_EN_31TO1(v) \
    (((v) & FM_DE_EN_RSVD_DE_EN_31TO1) >> 1U)

#define BM_DE_EN_DE_ENABLE  (0x01U << 0U)

#define RE_EN_OFF   0xb4U

#define FM_RE_EN_RSVD_RE_EN_31TO1   (0x7fffffffU << 1U)
#define FV_RE_EN_RSVD_RE_EN_31TO1(v) \
    (((v) << 1U) & FM_RE_EN_RSVD_RE_EN_31TO1)
#define GFV_RE_EN_RSVD_RE_EN_31TO1(v) \
    (((v) & FM_RE_EN_RSVD_RE_EN_31TO1) >> 1U)

#define BM_RE_EN_RE_ENABLE  (0x01U << 0U)

#define DET_OFF 0xb8U

#define FM_DET_RSVD_DE_DEAT_31TO24  (0xffU << 24U)
#define FV_DET_RSVD_DE_DEAT_31TO24(v) \
    (((v) << 24U) & FM_DET_RSVD_DE_DEAT_31TO24)
#define GFV_DET_RSVD_DE_DEAT_31TO24(v) \
    (((v) & FM_DET_RSVD_DE_DEAT_31TO24) >> 24U)

#define FM_DET_DE_DEASSERTION_TIME  (0xffU << 16U)
#define FV_DET_DE_DEASSERTION_TIME(v) \
    (((v) << 16U) & FM_DET_DE_DEASSERTION_TIME)
#define GFV_DET_DE_DEASSERTION_TIME(v) \
    (((v) & FM_DET_DE_DEASSERTION_TIME) >> 16U)

#define FM_DET_RSVD_DE_AT_15TO8 (0xffU << 8U)
#define FV_DET_RSVD_DE_AT_15TO8(v) \
    (((v) << 8U) & FM_DET_RSVD_DE_AT_15TO8)
#define GFV_DET_RSVD_DE_AT_15TO8(v) \
    (((v) & FM_DET_RSVD_DE_AT_15TO8) >> 8U)

#define FM_DET_DE_ASSERTION_TIME    (0xffU << 0U)
#define FV_DET_DE_ASSERTION_TIME(v) \
    (((v) << 0U) & FM_DET_DE_ASSERTION_TIME)
#define GFV_DET_DE_ASSERTION_TIME(v) \
    (((v) & FM_DET_DE_ASSERTION_TIME) >> 0U)

#define TAT_OFF 0xbcU

#define FM_TAT_RE_TO_DE (0xffffU << 16U)
#define FV_TAT_RE_TO_DE(v) \
    (((v) << 16U) & FM_TAT_RE_TO_DE)
#define GFV_TAT_RE_TO_DE(v) \
    (((v) & FM_TAT_RE_TO_DE) >> 16U)

#define FM_TAT_DE_TO_RE (0xffffU << 0U)
#define FV_TAT_DE_TO_RE(v) \
    (((v) << 0U) & FM_TAT_DE_TO_RE)
#define GFV_TAT_DE_TO_RE(v) \
    (((v) & FM_TAT_DE_TO_RE) >> 0U)

#define DLF_OFF 0xc0U

#define FM_DLF_RSVD_DLF (0xfffffffU << 4U)
#define FV_DLF_RSVD_DLF(v) \
    (((v) << 4U) & FM_DLF_RSVD_DLF)
#define GFV_DLF_RSVD_DLF(v) \
    (((v) & FM_DLF_RSVD_DLF) >> 4U)

#define FM_DLF_DLF  (0xfU << 0U)
#define FV_DLF_DLF(v) \
    (((v) << 0U) & FM_DLF_DLF)
#define GFV_DLF_DLF(v) \
    (((v) & FM_DLF_DLF) >> 0U)

#define RAR_OFF 0xc4U

#define FM_RAR_RSVD_RAR_31TO8   (0xffffffU << 8U)
#define FV_RAR_RSVD_RAR_31TO8(v) \
    (((v) << 8U) & FM_RAR_RSVD_RAR_31TO8)
#define GFV_RAR_RSVD_RAR_31TO8(v) \
    (((v) & FM_RAR_RSVD_RAR_31TO8) >> 8U)

#define FM_RAR_RAR  (0xffU << 0U)
#define FV_RAR_RAR(v) \
    (((v) << 0U) & FM_RAR_RAR)
#define GFV_RAR_RAR(v) \
    (((v) & FM_RAR_RAR) >> 0U)

#define TAR_OFF 0xc8U

#define FM_TAR_RSVD_TAR_31TO8   (0xffffffU << 8U)
#define FV_TAR_RSVD_TAR_31TO8(v) \
    (((v) << 8U) & FM_TAR_RSVD_TAR_31TO8)
#define GFV_TAR_RSVD_TAR_31TO8(v) \
    (((v) & FM_TAR_RSVD_TAR_31TO8) >> 8U)

#define FM_TAR_TAR  (0xffU << 0U)
#define FV_TAR_TAR(v) \
    (((v) << 0U) & FM_TAR_TAR)
#define GFV_TAR_TAR(v) \
    (((v) & FM_TAR_TAR) >> 0U)

#define LCR_EXT_OFF 0xccU

#define FM_LCR_EXT_RSVD_LCR_EXT (0xfffffffU << 4U)
#define FV_LCR_EXT_RSVD_LCR_EXT(v) \
    (((v) << 4U) & FM_LCR_EXT_RSVD_LCR_EXT)
#define GFV_LCR_EXT_RSVD_LCR_EXT(v) \
    (((v) & FM_LCR_EXT_RSVD_LCR_EXT) >> 4U)

#define BM_LCR_EXT_TRANSMIT_MODE    (0x01U << 3U)

#define BM_LCR_EXT_SEND_ADDR    (0x01U << 2U)

#define BM_LCR_EXT_ADDR_MATCH   (0x01U << 1U)

#define BM_LCR_EXT_DLS_E    (0x01U << 0U)

#define CPR_OFF 0xf4U

#define FM_CPR_RSVD_CPR_31TO24  (0xffU << 24U)
#define FV_CPR_RSVD_CPR_31TO24(v) \
    (((v) << 24U) & FM_CPR_RSVD_CPR_31TO24)
#define GFV_CPR_RSVD_CPR_31TO24(v) \
    (((v) & FM_CPR_RSVD_CPR_31TO24) >> 24U)

#define FM_CPR_FIFO_MODE    (0xffU << 16U)
#define FV_CPR_FIFO_MODE(v) \
    (((v) << 16U) & FM_CPR_FIFO_MODE)
#define GFV_CPR_FIFO_MODE(v) \
    (((v) & FM_CPR_FIFO_MODE) >> 16U)

#define FM_CPR_RSVD_CPR_15TO14  (0x3U << 14U)
#define FV_CPR_RSVD_CPR_15TO14(v) \
    (((v) << 14U) & FM_CPR_RSVD_CPR_15TO14)
#define GFV_CPR_RSVD_CPR_15TO14(v) \
    (((v) & FM_CPR_RSVD_CPR_15TO14) >> 14U)

#define BM_CPR_DMA_EXTRA    (0x01U << 13U)

#define BM_CPR_UART_ADD_ENCODED_PARAMS  (0x01U << 12U)

#define BM_CPR_SHADOW   (0x01U << 11U)

#define BM_CPR_FIFO_STAT    (0x01U << 10U)

#define BM_CPR_FIFO_ACCESS  (0x01U << 9U)

#define BM_CPR_ADDITIONAL_FEAT  (0x01U << 8U)

#define BM_CPR_SIR_LP_MODE  (0x01U << 7U)

#define BM_CPR_SIR_MODE (0x01U << 6U)

#define BM_CPR_THRE_MODE    (0x01U << 5U)

#define BM_CPR_AFCE_MODE    (0x01U << 4U)

#define FM_CPR_RSVD_CPR_3TO2    (0x3U << 2U)
#define FV_CPR_RSVD_CPR_3TO2(v) \
    (((v) << 2U) & FM_CPR_RSVD_CPR_3TO2)
#define GFV_CPR_RSVD_CPR_3TO2(v) \
    (((v) & FM_CPR_RSVD_CPR_3TO2) >> 2U)

#define FM_CPR_APB_DATA_WIDTH   (0x3U << 0U)
#define FV_CPR_APB_DATA_WIDTH(v) \
    (((v) << 0U) & FM_CPR_APB_DATA_WIDTH)
#define GFV_CPR_APB_DATA_WIDTH(v) \
    (((v) & FM_CPR_APB_DATA_WIDTH) >> 0U)

#define UCV_OFF 0xf8U

#define FM_UCV_UART_COMPONENT_VERSION   (0xffffffffU << 0U)
#define FV_UCV_UART_COMPONENT_VERSION(v) \
    (((v) << 0U) & FM_UCV_UART_COMPONENT_VERSION)
#define GFV_UCV_UART_COMPONENT_VERSION(v) \
    (((v) & FM_UCV_UART_COMPONENT_VERSION) >> 0U)

#define CTR_OFF 0xfcU

#define FM_CTR_PERIPHERAL_ID    (0xffffffffU << 0U)
#define FV_CTR_PERIPHERAL_ID(v) \
    (((v) << 0U) & FM_CTR_PERIPHERAL_ID)
#define GFV_CTR_PERIPHERAL_ID(v) \
    (((v) & FM_CTR_PERIPHERAL_ID) >> 0U)

#define THR_OFF     0x0U    /* wr */
#define DLL_OFF     0x0U    /* wr with dlab=1 */
#define DLH_OFF     0x4U    /* write with dlab=1 */
#define FCR_OFF     0x8U

#define FM_FCR_RT       (0x03U << 6U)
#define FV_FCR_RT(v) \
    (((v) << 6) & FM_FCR_RT)

#define FM_FCR_TET      (0x03U << 4U)
#define FV_FCR_TET(v) \
    (((v) << 4) & FM_FCR_TET)

#define BM_FCR_DMAM     (0x01U << 3U)
#define BM_FCR_XFIFOR   (0x01U << 2U)
#define BM_FCR_RFIFOR   (0x01U << 1U)
#define BM_FCR_FIFOE    (0x01U << 0U)

typedef struct {
    volatile uint32_t rbr;  /* offset: 0x0 */
    volatile uint32_t ier;  /* offset: 0x4 */
    volatile uint32_t iir;  /* offset: 0x8 */
    volatile uint32_t lcr;  /* offset: 0xc */
    volatile uint32_t mcr;  /* offset: 0x10 */
    volatile uint32_t lsr;  /* offset: 0x14 */
    volatile uint32_t msr;  /* offset: 0x18 */
    volatile uint32_t scr;  /* offset: 0x1c */
    uint8_t rsvd0[16];
    volatile uint32_t srbr0;  /* offset: 0x30 */
    volatile uint32_t srbr1;  /* offset: 0x34 */
    volatile uint32_t srbr2;  /* offset: 0x38 */
    volatile uint32_t srbr3;  /* offset: 0x3c */
    volatile uint32_t srbr4;  /* offset: 0x40 */
    volatile uint32_t srbr5;  /* offset: 0x44 */
    volatile uint32_t srbr6;  /* offset: 0x48 */
    volatile uint32_t srbr7;  /* offset: 0x4c */
    volatile uint32_t srbr8;  /* offset: 0x50 */
    volatile uint32_t srbr9;  /* offset: 0x54 */
    volatile uint32_t srbr10;  /* offset: 0x58 */
    volatile uint32_t srbr11;  /* offset: 0x5c */
    volatile uint32_t srbr12;  /* offset: 0x60 */
    volatile uint32_t srbr13;  /* offset: 0x64 */
    volatile uint32_t srbr14;  /* offset: 0x68 */
    volatile uint32_t srbr15;  /* offset: 0x6c */
    volatile uint32_t far;  /* offset: 0x70 */
    volatile uint32_t tfr;  /* offset: 0x74 */
    volatile uint32_t rfw;  /* offset: 0x78 */
    volatile uint32_t usr;  /* offset: 0x7c */
    volatile uint32_t tfl;  /* offset: 0x80 */
    volatile uint32_t rfl;  /* offset: 0x84 */
    volatile uint32_t srr;  /* offset: 0x88 */
    volatile uint32_t srts;  /* offset: 0x8c */
    volatile uint32_t sbcr;  /* offset: 0x90 */
    volatile uint32_t sdmam;  /* offset: 0x94 */
    volatile uint32_t sfe;  /* offset: 0x98 */
    volatile uint32_t srt;  /* offset: 0x9c */
    volatile uint32_t stet;  /* offset: 0xa0 */
    volatile uint32_t htx;  /* offset: 0xa4 */
    volatile uint32_t dmasa;  /* offset: 0xa8 */
    volatile uint32_t tcr;  /* offset: 0xac */
    volatile uint32_t de_en;  /* offset: 0xb0 */
    volatile uint32_t re_en;  /* offset: 0xb4 */
    volatile uint32_t det;  /* offset: 0xb8 */
    volatile uint32_t tat;  /* offset: 0xbc */
    volatile uint32_t dlf;  /* offset: 0xc0 */
    volatile uint32_t rar;  /* offset: 0xc4 */
    volatile uint32_t tar;  /* offset: 0xc8 */
    volatile uint32_t lcr_ext;  /* offset: 0xcc */
    uint8_t rsvd1[36];
    volatile uint32_t cpr;  /* offset: 0xf4 */
    volatile uint32_t ucv;  /* offset: 0xf8 */
    volatile uint32_t ctr;  /* offset: 0xfc */
} DW_apb_uart_t;

#endif  /* __DW_APB_UART_REG_H__ */
